title: "Munkh-Erdene.E"
description: "Computer Science student | Blogs, Labs"
baseurl: ""
url: "https://mnkrdnee.github.io"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme


nav:
  - name: "Home"
    link: "/"
  - name: "Blogs"
    link: "/blogs/"
  - name: "Labs"
    link: "/labs/"
  - name: "About"
    link: "/about/"
